apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger1
  labels:
    app: pinger1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger1
  template:
    metadata:
      labels:
        app: pinger1
    spec:
      containers:
      - name: pinger1
        image: namespace/pinger:1
        command: ["-remote", "http://pinger2:8762"]
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: pinger1
spec:
  selector:
    app.kubernetes.io/name: pinger
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
